services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - node.name=elasticsearch-node-172.20.178.149
      - discovery.seed_hosts=172.20.178.149
      - cluster.initial_master_nodes=172.20.178.149
      - ELASTIC_PASSWORD=campusdual
      - ELASTIC_USER=elastic
      - xpack.security.enabled=false  # Habilitar la seguridad
      - ingest.geoip.downloader.enabled=false # Deshabilitar la descarga de base de datos GeoIP
      - ES_JAVA_OPTS=-Xms7g -Xmx7g  # Asigna 15 GB de memoria mínima y máxima para Elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 7g           # Limita el contenedor a 15 GB de RAM
        reservations:
          memory: 7g           # Reserva 15 GB de RAM para Elasticsearch
          cpus: '1'           # Reserva 0.5 núcleos de CPU (se mantiene por si necesitas reservas mínimas de CPU)

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic_network:
    driver: bridge
