services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    network_mode: bridge
    environment:
      - cluster.name=es-cluster
      - node.name=elasticsearch-node-172.29.59.22
      #- node.name=elasticsearch-node-1
      - discovery.seed_hosts=172.29.59.22
      - cluster.initial_master_nodes=elasticsearch-node-172.29.59.22
      #- cluster.initial_master_nodes=172.29.59.22     
      - ELASTIC_PASSWORD=campusdual
      - ELASTIC_USER=elastic
      #- discovery.type: single-node
      - xpack.security.enabled=false  # Habilitar la seguridad
      - ingest.geoip.downloader.enabled=false # Deshabilitar la descarga de base de datos GeoIP
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Asigna 15 GB de memoria mínima y máxima para Elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4g           # Limita el contenedor a 15 GB de RAM
        reservations:
          memory: 2g           # Reserva 15 GB de RAM para Elasticsearch
          cpus: '1'           # Reserva 0.5 núcleos de CPU (se mantiene por si necesitas reservas mínimas de CPU)

volumes:
  elasticsearch_data:
    driver: local

