services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - node.name=${HOSTNAME}
      - network.host=0.0.0.0
      - discovery.type=zen-disco
      - discovery.seed_hosts=${SEED_HOSTS}
      - cluster.initial_master_nodes=${SEED_HOSTS}
      - ELASTIC_PASSWORD=campusdual
      - ELASTIC_USER=elastic
      - xpack.security.enabled=true  # Habilitar la seguridad
      - ingest.geoip.downloader.enabled=false  # Deshabilitar la descarga de base de datos GeoIP
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 5

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic_network:
    driver: bridge
