---
- name: Configure Elasticsearch Nodes
  hosts: all
  become: yes
  vars:
    seed_file: /home/ubuntu/seed_hosts.txt
    docker_compose_file: /home/ubuntu/docker-compose.yml  # Ruta de destino para el archivo docker-compose.yml

  tasks:
    - name: Copy seed_hosts.txt to the node
      copy:
        src: ./seed_hosts.txt
        dest: "{{ seed_file }}"
        mode: '0644'

    - name: Copy docker-compose.yml to the node
      copy:
        src: ./docker-compose.yml  # Ruta local del archivo docker-compose.yml
        dest: "{{ docker_compose_file }}"  # Ruta de destino en la instancia EC2
        mode: '0644'

    - name: Get private IP of the current host
      set_fact:
        PRIVATE_IP: "{{ ansible_default_ipv4.address }}"

    - name: Debug PRIVATE value
      debug:
        msg: "PRIVATE_IP:{{ PRIVATE_IP }}"

    - name: Slurp seed_hosts.txt file to fetch its contents
      slurp:
        src: "{{ seed_file }}"
      register: seed_file_content
    
    - name: Check decoded content of seed_hosts.txt
      debug:
        msg: "Seed hosts content: {{ seed_file_content.content | b64decode }}"

    - name: Clean the seed hosts content (remove carriage returns and newlines)
      set_fact:
        cleaned_seed_hosts: "{{ seed_file_content.content | b64decode | replace('\r', '') | replace('\n', '') }}"

    - name: Set SEED_HOSTS variable by excluding the private IP using reject
      set_fact:
        SEED_HOSTS: "{{ cleaned_seed_hosts | split(',') | reject('equalto', PRIVATE_IP) | join(',') }}"


    - name: Debug SEED_HOSTS value
      debug:
        msg: "SEED_HOSTS: {{ SEED_HOSTS }}"

    - name: Set environment variable for SEED_HOSTS
      shell: |
        echo "export SEED_HOSTS={{ SEED_HOSTS }}" >> /home/ubuntu/.bashrc

    - name: Start Elasticsearch with Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/ubuntu
